version: '3.8'

services:
  news-bot:
    build: .
    container_name: news_tel_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16-alpine
    container_name: news_bot_db
    restart: always
    environment:
      POSTGRES_DB: news_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: